GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/1
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Tai Tai",
    "number": "09972352449"
}