GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/1
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Timmy",
    "number": "56-45-9876854"
}